### ISSUE TITLE
common.c中的80端口是否可以改为其他端口呢，adhomeweb页面不想使用80

### ISSUE THREAD

**Issue by hhls** [dnomd343/ClearDNS#1]
host模式，初始化adhome时改为8899后，在不重启的情况下可以通过8899端口访问adhome，但是一旦重启，即便修改adhome的yaml文件修改重启还是80

**Comment by hhls** [comment]
adhome的yaml文件修改重启还是80

**Comment by dnomd343** [comment]
目前源码固定了80端口，后续会添加自定义的端口选项，您这边可以先fork源码修改编译。
