### ISSUE TITLE
bug:routerOS docker import error

### ISSUE THREAD

**Issue by happyDQN** [dnomd343/ClearDNS#10]
was unable to import

**Comment by dnomd343** [comment]
We need more information to determine the cause of the problem, can you provide a specific error log.

**Comment by happyDQN** [comment]
这家伙就是全部了，routerOS CHR 7.10.1docker import remote image failed,提示 无法导入，error。

**Comment by dnomd343** [comment]
不好意思这几天比较忙😭这没报错信息，我手头也没设备调试，不好解决呀🥲

**Comment by happyDQN** [comment]
又试了下，现在可以用了。
