### ISSUE TITLE
cleardns.yml配置文件

### ISSUE THREAD

**Issue by KnotDing** [dnomd343/ClearDNS#6]
启动参数可以使用--config指定配置文件路径，但是文档中似乎没有提及？是否可以在文档中补充这一点？

**Comment by KnotDing** [comment]
另外，adguard的相关配置似乎没做持久化，比如DNS重写，DNS拦截清单等相关配置，重启就丢失了

**Comment by dnomd343** [comment]
感谢提醒，文档中的确缺失了这部分选项介绍，本周内会补上。

adguard配置文件默认缓存在工作目录的 `adguard` 目录下，该目录在docker启动时是否有映射到主机？如果仍有错误，您可以在启动时加入 `--verbose` 选项获取详细的日志信息。

**Comment by KnotDing** [comment]
`ClearDNS 会将数据持久化存储，以在重启 Docker 或宿主机后保留配置及日志，上述命令将文件存储在工作目录 /etc/cleardns 下，您可以根据需要更改此目录。`，文档中提及了数据持久化的内容，但是实际上adguard在界面上做的相关配置并没有持久化到` /etc/cleardns `目录下。

**Comment by dnomd343** [comment]
AdGuardHome 在网页端的配置会被存储至工作目录下的 `./adguard/AdGuardHome.yaml` 中，您可以查看该文件是否发生过变化？或者，是否您在启动 docker 容器时，将 `--volume` 命令的映射方向写反了？这也可能导致这个问题。

您可以列出工作文件夹下（即文档中提及的 `/etc/cleardns/` 文件夹）的目录结构，或者提供一下运行日志。

**Comment by KnotDing** [comment]
目录下只包含如下文件：
![image](https://user-images.githubusercontent.com/27811621/227726123-9896ef26-f24e-485c-b75c-2d264e38da28.png)
并没有`adguard`文件夹

**Comment by dnomd343** [comment]
噢，确实是映射错目录了，这里是把容器内部的 `/etc/cleardns/` 目录映射出来了（这是内部的缓存目录），正确的做法应该是映射 `/cleardns/` 目录。

教程中是把宿主机的 `/etc/cleardns/` 同步至容器内的 `/cleardns/` 目录，如下：

```bash
docker … —volume /etc/cleardns/:/cleardns/ …
```

请检查启动命令中这两个目录是否倒置了。

**Comment by KnotDing** [comment]
抱歉，是我配置错误了，这个issue我关闭了。
