### ISSUE TITLE
最新版本的docker 镜像国内DNS解析异常

### ISSUE THREAD

**Issue by lcylgs** [dnomd343/ClearDNS#9]
版本[latest](https://hub.docker.com/layers/dnomd343/cleardns/latest/images/sha256-ff0c64f14bb39bda420b8321ed0baa6bf8ae7e1d82f8dd71a423032f60a83cee?context=explore)
国内DNS解析异常，现象为部分网站图片无法加载。

退回[v1.3.5](https://hub.docker.com/layers/dnomd343/cleardns/v1.3.5/images/sha256-cd5bef3d0bd778a5147321a2a13dba192433264df5d257462d919f81d1fd7f8c?context=explore)
后回复正常。

**Comment by dnomd343** [comment]
可否在无法加载图片的网页上，按 F12 进入开发者模式，在网络选项中查看图片资源 URL 所在域名，或在 AdGuardHome 日志中查找解析出错的上游返回值，提交一下这些具体信息帮助定位错误。

从 1.3.5 升级到 latest 版本，其中变动仅在于编译新稳定版 dnsproxy 与 AdGuardHome，这个问题大概率是 ADG 团队在上游更新了某些东西导致的。

PS: AdGuardHome 的 `v0.107.31` 版本就因为严重 bug 重发了 hotfix，有可能是它还存在其他问题。

**Comment by dnomd343** [comment]
您可以尝试最新版的镜像，它升级 AdGuardHome 至 [v0.107.33](https://github.com/AdguardTeam/AdGuardHome/releases/tag/v0.107.33) 版本，该版本存在诸多错误修复，可能已解决 issue 问题。

**Comment by lcylgs** [comment]
> 

昨晚尝试升级后问题依旧。之前忘说了，用新版本后微软teams，office的解析有也问题，teams提示离线，office一直在连接服务器，更换DNS后就恢复正常。

**Comment by lcylgs** [comment]
我看了一下docker日志，报错是ADG启动失败：unknown configuration schema version 23
查询到https://github.com/AdguardTeam/AdGuardHome/issues/2458
解决办法是删除映射目录下的adguard文件夹，然后重启即可。
应该是不同版本的ADG不兼容。

**Comment by dnomd343** [comment]
喔😲居然是这个导致的，解决了就好
